
/**
* DBHandlerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBHandler.idl
* Thursday, August 16, 2018 8:09:52 o'clock PM PDT
*/

public interface DBHandlerOperations 
{
  void addClient (String mac, String ipAddress, int port);
  boolean clientExist (String mac);
  void updateIPAddress (String mac, String ipAddress);
  void updatePort (String mac, int port);
  void shareFile (String filename, String fsize, String mac);
  void removeFile (String filename, String mac);
  boolean isShared (String filename, String mac);
  boolean fileExist (String filename, String mac);
  String search (String filename, String mac);
  String downloadFile (String filename, String mac);
} // interface DBHandlerOperations
