
/**
* DBHandlerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBHandler.idl
* Thursday, August 16, 2018 8:09:52 o'clock PM PDT
*/

public final class DBHandlerHolder implements org.omg.CORBA.portable.Streamable
{
  public DBHandler value = null;

  public DBHandlerHolder ()
  {
  }

  public DBHandlerHolder (DBHandler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DBHandlerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DBHandlerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DBHandlerHelper.type ();
  }

}
