
/**
* DBHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DBHandler.idl
* Thursday, August 16, 2018 8:09:52 o'clock PM PDT
*/

public interface DBHandler extends DBHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DBHandler
